[effect_item_tooltips]
	#Add descriptions to item tooltips.
	#Default Value: ALWAYS
	#Allowed Values: NEVER, SHIFT, ALWAYS
	item_descriptions = "ALWAYS"
	#Display potion effects for food item tooltips.
	#Default Value: true
	food_effect_tooltips = true
	#Apply a fixed string before every description line.
	#Supports formatting codes which will also apply to the description for setting custom text colors and styles.
	#https://minecraft.wiki/w/Formatting_codes
	#Default Value: §7 ◆ §r
	tooltip_line_decorations = "§7 ◆ §r"

	[effect_item_tooltips.item_tooltip_lines]
		#Add the internal id to tooltips.
		#Default Value: false
		internal_name = false
		#Add the description to tooltips.
		#Default Value: true
		value_description = true
		#Add the name of the source mod to tooltips.
		#Default Value: false
		mod_name = false

	[effect_item_tooltips.item_description_targets]
		#Add effect descriptions to food items, e.g. rotten flesh and raw chicken.
		#Default Value: true
		consumable = true
		#Add effect descriptions to suspicious stew items.
		#Default Value: true
		suspicious_stew = true
		#Add effect descriptions to potion items, e.g. potion, splash potion, lingering potion, and tipped arrow.
		#Default Value: true
		potion_contents = true
		#Add effect descriptions to ominous bottle items.
		#Default Value: true
		ominous_bottle = true

[effect_widget_tooltips]
	#Add rich tooltips including effect descriptions to effect widgets in inventory screens.
	#Default Value: true
	widget_tooltips = true
	#Apply a fixed string before every description line.
	#Supports formatting codes which will also apply to the description for setting custom text colors and styles.
	#https://minecraft.wiki/w/Formatting_codes
	#Default Value: §7 ◆ §r
	tooltip_line_decorations = "§7 ◆ §r"

	[effect_widget_tooltips.widget_tooltip_lines]
		#Add the internal id to tooltips.
		#Default Value: false
		internal_name = false
		#Add the name of the source mod to tooltips.
		#Default Value: false
		mod_name = false
		#Add attributes granted by an effect to tooltips.
		#Default Value: true
		effect_attributes = true
		#Add the description to tooltips.
		#Default Value: true
		value_description = true
		#Add the effect name and duration to tooltips.
		#Default Value: true
		display_name = true
